name: C Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Compiler installieren (falls notwendig)
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Code kompilieren
        run: gcc -o main main.c

      - name: Zeige erstellte Datei
        run: ls -lh

      - name: Programm ausführen (optional)
        run: ./main

      - name: Build-Artefakt hochladen
        uses: actions/upload-artifact@v4
        with:
          name: MeinProgramm
          path: main*  # Linux/macOS (ohne .exe) & Windows (.exe)
