name: CMake Build Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Abhängigkeiten installieren
        run: sudo apt-get update && sudo apt-get install -y cmake gcc

      - name: Build-Verzeichnis erstellen
        run: mkdir -p build

      - name: CMake konfigurieren
        run: cd build && cmake ..

      - name: Code kompilieren
        run: cd build && make

      - name: Zeige erstellte Datei
        run: dir build\
        
      - name: Programm ausführen (optional)
        run: ./build/program

      - name: Build-Artefakt hochladen
        uses: actions/upload-artifact@v4
        with:
          name: Programm-Windows
          path: build/program*  # Linux/macOS (ohne .exe) & Windows (.exe)

