name: Unit Tests

on:
  workflow_dispatch:


jobs:
  unitTest:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y gcc libcriterion-dev

      - name: Compile tests
        run: gcc -o build/test_main src/test_main.c -lcriterion

      - name: Run tests
        run: ./build/test_main
